site_name: Helium CMS Documentation
site_url: https://example.com/
theme: material
docs_dir: src
site_dir: html
markdown_extensions:
  - admonition
nav:
  - index.md
  - configuration.md
  - handlers.md
  - entities.md
